porting this plugin base on version sf
EC-CUBE/custom-csv-export-plugin pull request #13
Opened 2018-06-29 07:41 UTC by hoand-vn

## 概要(Overview・Refs Issue)
+ PullRequestの目的、関連するIssue番号など

## 方針(Policy)
+ このPullRequestを作るにあたって考慮したものや除外した内容
  - Change some logic business ( calculation price )

## 実装に関する補足(Appendix)
+ will continue change for official version

2018-07-10 06:55 UTC, ryo-endo requested changes

2018-07-10 06:55 UTC, ryo-endo commented on Resource/template/Admin/index.twig
> +{% extends '@admin/styleguide_frame.twig' %}
use '@admin/default_frame.twig'

2018-07-10 06:56 UTC, ryo-endo requested changes
不正なSQLを入力したときに、エラーが発生します。

▼エラー
```
Attempted to call an undefined method named "buildViolation" of class "Plugin\CustomCsvExport\Validator\SqlCheckValidator".
```

▼入力例
![image](https://user-images.githubusercontent.com/16891862/42493943-c11656e6-8459-11e8-9952-0232ddaa2824.png)

2018-07-10 08:45 UTC, ryo-endo requested changes
何も入力せずに「登録」した場合に、エラーが表示されません。
3.0系では、添付ファイルのように表示されています。
![image](https://user-images.githubusercontent.com/16891862/42499156-0406ff00-8469-11e8-9ae2-707e64d0dc99.png)

2018-07-19 07:26 UTC, hoand-vn commented
for fixing convention

2018-07-19 09:54 UTC, hoand-vn commented
finish fixing

2019-05-11 22:15 UTC, Yangsin commented
対応を見直すため一度クローズします。

2019-05-11 22:15 UTC, closed without merging